### ISSUE TITLE
Clarifying observations around unexpected scaling down behavior

### ISSUE THREAD

**Issue by kelvintaywl** [hashicorp/nomad-autoscaler#612] opened 2023-01-27 03:43 UTC
Hi folks 👋 

Thanks so much for providing this tooling!

We observed the Nomad Autoscaler scaling down unexpectedly during a brief period.
What we also saw was that right before scaling down, there were warning messages re: `failed to ACK policy evaluation`.
A snippet of our logs can be found here:

```
2023-01-12T16:13:33.420Z [WARN]  policy_eval.worker: failed to ACK policy evaluation: eval_id=<redacted> eval_token=<redacted> id=<redacted> policy_id=<redacted> queue=cluster error="evaluation ID not found"
2023-01-12T16:15:34.302Z [INFO]  policy_eval.worker: scaling target: id=<redacted> queue=cluster target=aws-asg from=16 to=14 reason="scaling down because factor is 0.866009" meta=map[nomad_policy_id:<redacted>]

...

2023-01-12T16:22:12.792Z [WARN]  policy_eval.worker: failed to ACK policy evaluation: eval_id=<redacted> eval_token=<redacted> id=<redacted> policy_id=<redacted> queue=cluster error="evaluation ID not found"
2023-01-12T16:24:13.795Z [INFO]  policy_eval.worker: scaling target: id=<redacted> policy_id=<redacted> queue=cluster target=aws-asg from=14 to=13 reason="scaling down because factor is 0.862636" meta=map[nomad_policy_id:<redacted>]
```

Our current hypothesis is that:

- this `failed to ACK policy evaluation` error results in checks failing
- which results in the Autoscaler scaling down, as per v0.3.5 (discussed here in #562), before the adding of `on_error` configuration in v0.3.6 (#566)

However, with a limited understanding of Autoscaler under the hood, would this hypothesis be correct?

If this is correct indeed, what is the significance of the `failed to ACK policy evaluation` error, and how can one prevent it?
Would you suggest upgrading to the latest @ v0.3.7 for instance?

### Some details:

- Nomad Autoscaler version: v0.3.5
- scaling policy:

```hcl
      policy {
        cooldown = "2m"
        evaluation_interval = "1m"
        check "cpu_allocated_percentage" {
          source = "nomad-apm"
          query  = "percentage-allocated_cpu"
          strategy "target-value" {
            target = 70
          }
        }
        check "mem_allocated_percentage" {
          source = "nomad-apm"
          query = "percentage-allocated_memory"
          strategy "target-value" {
            target = 70
          }
        }
      }  
```

Thank you once again! 🙇

**Comment by jkzilla** [comment] 2023-02-23 22:35
cc @jrasell if you have any insight on the above? (saw your comment on the last open issue)

**Comment by e-grapp** [comment] 2023-03-08 20:34
Hello Hashicorp folks - we are just following up to see if the team has any insight on the above that we can share with a user running into issues with the `nomad-autoscaler` - Thank you!

**Comment by lgfa29** [comment] 2023-07-15 01:23
Hi all 👋 Apologies for the delay here.

I don't see anything particular wrong here. `failed to ACK policy evaluation` is an error that should not happen, but this particular error in specific (`evaluation ID not found`) is pretty much harmless as it basically means there's nothing to do, the evaluation is not waiting to be ACK'ed (in hindsight, this shouldn't be an error at all).

I do see two scaling down actions, one `from=16 to=14` and another `from=14 to=13` and both happened because the metric was off target. I don't know if you had the change to read the docs for the `target-value` plugin recently, but I have updated a while back to give more details on how it calculates things internally:
https://developer.hashicorp.com/nomad/tools/autoscaling/plugins/strategy/target-value

In the first cause, you had a factor of `0.866009`. With a target of `70` this means that either your allocated CPU or memory percentage was at `0.866009 * 70 = 60.62063`, which is below the target, so the autoscaler removed two instances because `0.866009 * 16 = 13.856144 ~= 14`, and this brings your usage closer to the target of 70.

The next down scale is similar. Factor of `0.862636` means CPU or memory was about `60.38452` so it reduce the number of instances to `14 * 0.862636 ~= 13`.

If these actions are unexpected to you I suspect your policy may not reflect your intentions. What were you expecting to happen?

Or if the problem is that you don't want to have so many actions in such a short time I would suggest you either increase your `evaluation_interval` or your `cooldown`.

**Comment by lgfa29** [comment] 2023-12-21 04:34
Closing this as the previous answer seems to have clarified that the behaviour described here is the expected result. Feel free to reach out if you have any more questions!

**Closed by lgfa29** 2023-12-21 04:34 UTC
Labels: stage/waiting-reply, theme/policy-eval, type/question
