### ISSUE TITLE
AWS ASG Horizontal Cluster Scale has insufficient permissions in documentation

### ISSUE THREAD

**Issue by rahadiangg** [hashicorp/nomad-autoscaler#952] opened 2024-08-14 13:41 UTC
## Issue

Nomad autoscaler for AWS ASG has insufficient permission `autoscaling:DescribeInstanceRefreshes` in [documentation](https://developer.hashicorp.com/nomad/tools/autoscaling/plugins/target/aws-asg#agent-configuration-options) 

## Log Nomad Autoscaler

```
2024-08-14T13:28:37.180Z [ERROR] policy_eval.worker: failed to evaluate policy: eval_id=1ca75fe9-f074-f4c0-cebe-ec59a2385bbd eval_token=076b3c77-c555-e48d-6600-2cc0bc9a16f1 id=fca667a3-c166-1233-a119-70f706da1dce policy_id=d35764c2-a165-3229-4507-e04f65a0a80c queue=cluster error="failed to scale target: failed to describe AWS InstanceRefresh: operation error Auto Scaling: DescribeInstanceRefreshes, https response error StatusCode: 403, RequestID: fd3fc799-f838-4484-aa6c-096d170b7721, api error AccessDenied: User: arn:aws:iam::613883536084:user/nomad-autoscaler-asg is not authorized to perform: autoscaling:DescribeInstanceRefreshes because no identity-based policy allows the autoscaling:DescribeInstanceRefreshes action"
2024-08-14T13:28:37.180Z [DEBUG] policy_eval.broker: nack eval: eval_id=1ca75fe9-f074-f4c0-cebe-ec59a2385bbd token=076b3c77-c555-e48d-6600-2cc0bc9a16f1
```

**Comment by tgross** [comment] 2024-08-14 13:43
Hi @rahadiangg! Looks like this is a dupe of https://github.com/hashicorp/nomad-autoscaler/issues/884

**Closed by tgross** 2024-08-14 13:43 UTC
